apiVersion: v1
kind: Service
metadata:
  labels:
    app: poc-front-app
  name: poc-front-appsvc
  namespace: poc-front-app
spec:
  ports:
  - name: poc-front-appsvc
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: poc-front-app
  type: ClusterIP
status:
  loadBalancer: {}