admin:
  # Enable Admin API
  enabled: true
  # admin service type
  type: ClusterIP
  # loadBalancerIP: a.b.c.d
  # loadBalancerSourceRanges:
  #   - "143.231.0.0/16"
  externalIPs: []

  #
  port: 9180
  servicePort: 9180
  nodePort: 32000
  # Admin API support CORS response headers
  cors: true
  # Admin API credentials
  credentials:
    admin: edd1c9f034335f136f87ad84b625c8f1
    viewer: 4054f7cf07e344346cd3f287985e76a2

  allow:
    # The ip range for allowing access to Apache APISIX
    ipList:
      - 127.0.0.1/24
      - 172.18.0.1/24
gateway:
  http:
    enabled: true
    nodePort: 30080
  tls:
    enabled: true
    nodePort: 30443
dashboard:
  enabled: true
  ingress:
    enabled: false
    # Kubernetes 1.18+ support ingressClassName attribute
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # domain access apisix example:
    # hosts:
    # - host: apisix-dashboard.local
    #    paths:
    #     - /*
    hosts:
      - host: apisix-dashboard.demo.jpgouin.pro
        paths: []
    tls: []

ingress-controller:
  enabled: true
  config:
    apisix:
      serviceName: apisix-admin
      serviceNamespace: apisix
      servicePort: 9180
      adminKey: "edd1c9f034335f136f87ad84b625c8f1"
      clusterName: "default"