# httpbin-route.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpserver-route
  namespace: keycloak
spec:
  http:
  - name: keycloak_rules
    match:
      hosts:
      - keycloak.192.168.59.106.nip.io
      paths:
      - /*
    backends:
       - serviceName: keycloak
         servicePort: 80
